### ISSUE TITLE
User Management Module

### ISSUE THREAD

**Issue by bsoetaer** [bsoetaer/CMPUT391Project#2]
This module allows a system administrator to manage (to enter or update) the user information, i.e., the information stored in tables users, persons, and family_doctor.

**Comment by Tyler-Meen** [comment]
looks like everything is working. May have to prettyfy if we decide to care.

**Comment by Tyler-Meen** [comment]
Hey I just noticed that according to marking guide Vincent posted, the user management doesn't need to be able to delete entries. Should i just take out that functionality?

**Comment by bsoetaer** [comment]
If you already implementrd it i see no reason to take it out. Just makes
morr work for you.
