### ISSUE TITLE
Data Analysis Module

### ISSUE THREAD

**Issue by bsoetaer** [bsoetaer/CMPUT391Project#6]
This module will be used by the system administrator (i.e., a user named "admin") to generate and display an OLAP report for data analysis.   A user of this module may choose to display the number of images for each patient ,  test type, and/or period of time.  For example, a user may choose to display the number of images for each patient; or display the number of images  for each test type for each month.

```
-One must generate a data cube information of the number of records for all the combinations of three columns, i.e., patient_name, test_type, and time(according to the values of column test_date).
-The user must be able to perform generalization (roll up) and specialization (drill down)  on three levels of time hierarchies,  i.e., weekly, monthly, and yearly.

-To speed up the OLAP operations, one might materialize the data cube information by creating a fact table/view storing all  information needed, including the lowest level of time hierarchy.
```

**Comment by Tyler-Meen** [comment]
Finished. Ran into some issues after testing, think it was my tomcat. After playing around on the website the connection to the database would fail. not sure if its the code or just tomcat being an asshole. If its still doing it tomorrow ill look into it.
